[build]
  base = "front/"
  command = "yarn build"
  build = "build/"

[context.production]
  environment = { NODE_VERSION = "14.18.0" }

[build.environment]
  GENERATE_SOURCEMAP = "true"

[build.production.environment]
  GENERATE_SOURCEMAP = "true"