export const email = 'playwright@test.com';
export const password = 'password123';

const popularShows = [
  {
    backdrop_path: '/y7OFTnu8Gh2KHWX0Y05y8OY9kCB.jpg',
    id: 232766,
    name: 'Mercy for None',
    original_name: '광장',
    overview:
      "After severing ties with his gang, a former gangster returns to uncover the truth behind his brother's death — embarking on a relentless path of revenge.",
    poster_path: '/yOtukBOsfPgn3T0Wq1DUxUWtj9j.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'ko',
    genre_ids: [10759],
    popularity: 5.4592,
    first_air_date: '2025-06-06',
    vote_average: 7.4,
    vote_count: 5,
    origin_country: ['KR'],
  },
  {
    backdrop_path: '/cxejGoxpynd144zaivyEKFxCktm.jpg',
    id: 247718,
    name: 'MobLand',
    original_name: 'MobLand',
    overview:
      'Two mob families clash in a war that threatens to topple empires and lives.',
    poster_path: '/abeH7n5pcuQcwYcTxG6DTZvXLP1.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [80, 18],
    popularity: 111.8993,
    first_air_date: '2025-03-30',
    vote_average: 8.47,
    vote_count: 168,
    origin_country: ['GB', 'US'],
  },
  {
    backdrop_path: '/uQ4lG7E7mlyKsGvbASftQ6Hu2IX.jpg',
    id: 100088,
    name: 'The Last of Us',
    original_name: 'The Last of Us',
    overview:
      'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.',
    poster_path: '/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [18],
    popularity: 203.4952,
    first_air_date: '2023-01-15',
    vote_average: 8.528,
    vote_count: 6157,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/nn9vM29SKN227zupaOOmaJz5SA0.jpg',
    id: 241554,
    name: 'Murderbot',
    original_name: 'Murderbot',
    overview:
      'In a high-tech future, a rogue security robot secretly gains free will. To stay hidden, it reluctantly joins a new mission protecting scientists on a dangerous planet...even though it just wants to binge soap operas.',
    poster_path: '/mIKfKo2uDk3itzAPYIcSeYr4KtF.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [35, 18, 10765],
    popularity: 83.248,
    first_air_date: '2025-05-15',
    vote_average: 7.125,
    vote_count: 96,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/wIoxMHbyUJnx5Fm9tI26hIYGI1D.jpg',
    id: 245703,
    name: 'Dept. Q',
    original_name: 'Dept. Q',
    overview:
      "A brash but brilliant cop becomes head of a new police department, where he leads an unlikely team of misfits in solving Edinburgh's cold cases.",
    poster_path: '/zOkpWMqpdIV1qeiEiArjaReKxzm.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [18, 80, 9648],
    popularity: 97.2203,
    first_air_date: '2025-05-29',
    vote_average: 7.908,
    vote_count: 61,
    origin_country: ['GB'],
  },
  {
    backdrop_path: '/lPmUu3xkoksz3xsa1feIUoOBZrg.jpg',
    id: 117581,
    name: 'Ginny & Georgia',
    original_name: 'Ginny & Georgia',
    overview:
      "Angsty and awkward fifteen year old Ginny Miller often feels more mature than her thirty year old mother, the irresistible and dynamic Georgia Miller. After years on the run, Georgia desperately wants to put down roots in picturesque New England and give her family something they've never had... a normal life. But it's not all carpool and Kombucha as Georgia's past threatens her and her family's new way of life... and Georgia will do anything to protect her family.",
    poster_path: '/vOwunzW4dx3n0J5mH40n9jTRSwY.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [35, 18],
    popularity: 35.6922,
    first_air_date: '2021-02-24',
    vote_average: 8.066,
    vote_count: 1619,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/Ao5pBFuWY32cVuh6iYjEjZMEscN.jpg',
    id: 60625,
    name: 'Rick and Morty',
    original_name: 'Rick and Morty',
    overview:
      "Rick is a mentally-unbalanced but scientifically gifted old man who has recently reconnected with his family. He spends most of his time involving his young grandson Morty in dangerous, outlandish adventures throughout space and alternate universes. Compounded with Morty's already unstable family life, these events cause Morty much distress at home and school.",
    poster_path: '/WGRQ8FpjkDTzivQJ43t94bOuY0.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 35, 10765, 10759],
    popularity: 161.1102,
    first_air_date: '2013-12-02',
    vote_average: 8.686,
    vote_count: 10194,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/kCGwvjpqM1owt9kI4pkYPJWJLvc.jpg',
    id: 83867,
    name: 'Andor',
    original_name: 'Andor',
    overview:
      'In an era filled with danger, deception and intrigue, Cassian Andor will discover the difference he can make in the struggle against the tyrannical Galactic Empire. He embarks on a path that is destined to turn him into a rebel hero.',
    poster_path: '/khZqmwHQicTYoS7Flreb9EddFZC.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [10765, 10759, 18],
    popularity: 55.0051,
    first_air_date: '2022-09-21',
    vote_average: 8.261,
    vote_count: 1544,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
    id: 37854,
    name: 'One Piece',
    original_name: 'ワンピース',
    overview:
      'Years ago, the fearsome Pirate King, Gol D. Roger was executed leaving a huge pile of treasure and the famous "One Piece" behind. Whoever claims the "One Piece" will be named the new King of the Pirates.\n\nMonkey D. Luffy, a boy who consumed a "Devil Fruit," decides to follow in the footsteps of his idol, the pirate Shanks, and find the One Piece. It helps, of course, that his body has the properties of rubber and that he\'s surrounded by a bevy of skilled fighters and thieves to help him along the way.\n\nLuffy will do anything to get the One Piece and become King of the Pirates!',
    poster_path: '/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'ja',
    genre_ids: [10759, 35, 16],
    popularity: 62.0434,
    first_air_date: '1999-10-20',
    vote_average: 8.7,
    vote_count: 4896,
    origin_country: ['JP'],
  },
  {
    backdrop_path: '/gDtZQmfzvErZpeXOVeCBQE9WkSF.jpg',
    id: 239770,
    name: 'Doctor Who',
    original_name: 'Doctor Who',
    overview:
      'The Doctor and his companion travel across time and space encountering incredible friends and foes.',
    poster_path: '/2JP6NSmBwxg75uTcIHiv5R8PpPi.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [10759, 18, 10765],
    popularity: 32.8891,
    first_air_date: '2024-05-11',
    vote_average: 6.4,
    vote_count: 220,
    origin_country: ['GB'],
  },
  {
    backdrop_path: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
    id: 66732,
    name: 'Stranger Things',
    original_name: 'Stranger Things',
    overview:
      'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    poster_path: '/uOOtwVbSr4QDjAGIifLDwpb2Pdl.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [18, 10765, 9648],
    popularity: 89.6423,
    first_air_date: '2016-07-15',
    vote_average: 8.597,
    vote_count: 18358,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/x7J7YydPEnTZm6JoTqbKOYkVb8e.jpg',
    id: 235924,
    name: 'Criminal Code',
    original_name: 'DNA DO CRIME',
    overview:
      'To crack the code of an investigation into a larger-than-life robbery, federal agents need to get creative.',
    poster_path: '/fDu0T5WE0QAoX2yAqZ1RtlWBn6I.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'pt',
    genre_ids: [18, 80, 10759],
    popularity: 52.9298,
    first_air_date: '2023-11-14',
    vote_average: 7.6,
    vote_count: 100,
    origin_country: ['BR'],
  },
  {
    backdrop_path: '/1SLimeCtDZhk9CCKj4qr435yvPT.jpg',
    id: 252640,
    name: 'Legend of Zang Hai',
    original_name: '藏海传',
    overview:
      '"Legend of Zang Hai" follows the son of Imperial Astronomer Kuai Duo. Consumed by vengeance, he spends a decade honing his skills. Assuming the name Zang Hai, he ventures into the capital to uncover the truth, avenge his family, and restore justice.',
    poster_path: '/6Nn2qwv2GrQ1cHkrgwCeSdEbbw8.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'zh',
    genre_ids: [18],
    popularity: 54.5394,
    first_air_date: '2025-05-18',
    vote_average: 8.3,
    vote_count: 14,
    origin_country: ['CN'],
  },
  {
    backdrop_path: '/tJSAxxjCtbtZYMBQkfxvdgqXsz5.jpg',
    id: 227191,
    name: 'Nine Puzzles',
    original_name: '나인 퍼즐',
    overview:
      'Ten years after discovering her murdered uncle, Ena and Detective Hansaem must cooperate to stop a series of similar murders - each linked by strange puzzle pieces.',
    poster_path: '/eQWEWCOg5LZLu2AihfMueiHGw1Y.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'ko',
    genre_ids: [80, 9648, 18],
    popularity: 43.8552,
    first_air_date: '2025-05-21',
    vote_average: 7.524,
    vote_count: 21,
    origin_country: ['KR'],
  },
  {
    backdrop_path: '/cBsAo9icWr0mZBvd4Rc0R4kxnDU.jpg',
    id: 291256,
    name: 'Sara - Woman in the Shadows',
    original_name: "Sara - La donna nell'ombra",
    overview:
      'The suspicious death of her son pushes a former secret agent back into action, investigating a series of crimes that grows increasingly sinister.',
    poster_path: '/9QVSjcrWGjV46DlSLfh9JI4oIaa.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'it',
    genre_ids: [9648, 18, 80],
    popularity: 47.4613,
    first_air_date: '2025-06-03',
    vote_average: 7.5,
    vote_count: 5,
    origin_country: ['IT'],
  },
  {
    backdrop_path: '/vcFW09U4834DyFOeRZpsx9x1D3S.jpg',
    id: 57243,
    name: 'Doctor Who',
    original_name: 'Doctor Who',
    overview:
      "The Doctor is a Time Lord: a 900 year old alien with 2 hearts, part of a gifted civilization who mastered time travel. The Doctor saves planets for a living—more of a hobby actually, and the Doctor's very, very good at it.",
    poster_path: '/93N9BsyMcAs5YESvuOCwEADhdhr.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [10759, 18, 10765],
    popularity: 169.8138,
    first_air_date: '2005-03-26',
    vote_average: 7.5,
    vote_count: 3138,
    origin_country: ['GB'],
  },
  {
    backdrop_path: '/25EBuAv16ZCsnxqJoDx0GwwQoSG.jpg',
    id: 253321,
    name: 'The Better Sister',
    original_name: 'The Better Sister',
    overview:
      "Chloe moves in New York's most elite circles with her lawyer husband Adam and teenage son Ethan by her side while her estranged sister Nicky tries to make ends meet and stay clean. When Adam is brutally murdered, the investigation sends shockwaves through the family and exposes long-buried secrets.",
    poster_path: '/vd1vEp1cKOkimarpuykswWR63Eg.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [18, 9648],
    popularity: 53.1427,
    first_air_date: '2025-05-29',
    vote_average: 7.2,
    vote_count: 18,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/8UuyKCIaX0MqcECmcgPxFCANkq4.jpg',
    id: 113959,
    name: 'Duster',
    original_name: 'Duster',
    overview:
      'In 1972, the first Black female FBI agent heads to the Southwest and recruits a gutsy getaway driver in a bold effort to take down a growing crime syndicate.',
    poster_path: '/wYBsKEFU0qHdhSI9QtQjL8HELMn.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [80, 18],
    popularity: 32.8702,
    first_air_date: '2025-05-15',
    vote_average: 5.611,
    vote_count: 18,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/5MWFjQ3NuNtNeOE9FdrVLeNMNPs.jpg',
    id: 1877,
    name: 'Phineas and Ferb',
    original_name: 'Phineas and Ferb',
    overview:
      'Each day, two kindhearted suburban stepbrothers on summer vacation embark on some grand new project, which annoys their controlling sister, Candace, who tries to bust them. Meanwhile, their pet platypus plots against evil Dr. Doofenshmirtz.',
    poster_path: '/g6TidT7be954rrzPPBTIXkSmfXj.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [16, 35, 10751, 10765],
    popularity: 137.2552,
    first_air_date: '2007-08-17',
    vote_average: 7.9,
    vote_count: 906,
    origin_country: ['US'],
  },
  {
    backdrop_path: '/zZqpAXxVSBtxV9qPBcscfXBcL2w.jpg',
    id: 1399,
    name: 'Game of Thrones',
    original_name: 'Game of Thrones',
    overview:
      "Seven noble families fight for control of the mythical land of Westeros. Friction between the houses leads to full-scale war. All while a very ancient evil awakens in the farthest north. Amidst the war, a neglected military order of misfits, the Night's Watch, is all that stands between the realms of men and icy horrors beyond.",
    poster_path: '/1XS1oqL89opfnbLl8WnZY1O1uJx.jpg',
    media_type: 'tv',
    adult: false,
    original_language: 'en',
    genre_ids: [10765, 18, 10759],
    popularity: 187.2638,
    first_air_date: '2011-04-17',
    vote_average: 8.457,
    vote_count: 25081,
    origin_country: ['US'],
  },
];

export const popularShowsResponse = {
  page: 1,
  results: popularShows,
  total_pages: 500,
  total_results: 10000,
};

export const searchLastOfUsResponse = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/uQ4lG7E7mlyKsGvbASftQ6Hu2IX.jpg',
      genre_ids: [18],
      id: 100088,
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'The Last of Us',
      overview:
        'Twenty years after modern civilization has been destroyed, Joel, a hardened survivor, is hired to smuggle Ellie, a 14-year-old girl, out of an oppressive quarantine zone. What starts as a small job soon becomes a brutal, heartbreaking journey, as they both must traverse the United States and depend on each other for survival.',
      popularity: 207.5127,
      poster_path: '/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg',
      first_air_date: '2023-01-15',
      name: 'The Last of Us',
      vote_average: 8.529,
      vote_count: 6159,
    },
    {
      adult: false,
      backdrop_path: null,
      genre_ids: [99],
      id: 62141,
      origin_country: [],
      original_language: 'en',
      original_name: 'The Last of Us Development Series',
      overview:
        'Through short documentary episodes, key features of The Last of Us  are shown.',
      popularity: 0.6865,
      poster_path: null,
      first_air_date: '2013-02-28',
      name: 'The Last of Us Development Series',
      vote_average: 9.5,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: '/hNYZJdciLyYXisxfaKgFn6QcKfQ.jpg',
      genre_ids: [99, 9648, 18],
      id: 67834,
      origin_country: ['US'],
      original_language: 'en',
      original_name: 'Autopsy: The Last Hours of...',
      overview:
        'Revealing the truth behind the controversial deaths of some of the most famous celebrities. Crucial medical evidence gained from the actual autopsies explains what killed the stars and reveals how they died, finally putting an end to the speculation.',
      popularity: 178.3658,
      poster_path: '/cSqKkfHiEJGHaWpZaOgjQeOE08b.jpg',
      first_air_date: '2014-01-07',
      name: 'Autopsy: The Last Hours of...',
      vote_average: 7.1,
      vote_count: 13,
    },
  ],
  total_pages: 1,
  total_results: 3,
};
